import Head from "next/head";

const HeadTag = () => {
  return (
    <Head>
      <title>雀Gate</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/雀Gate.png" />
    </Head>
  );
};

export default HeadTag;
